@startuml Flowgraph Kelola Pengguna Admin
skinparam activity {
    BackgroundColor #FFFFFF
    BorderColor #000000
    FontSize 12
    RoundCorner 15
}
skinparam activityDiamond {
    BackgroundColor #FFFFFF
    BorderColor #000000
    FontSize 12
}

start
:1;
:2;
:3;
if (4) then (yes)
    :5;
    :9;
    :10;
    :11;
    stop
else (no)
    :6;
    :7;
    :8;
endif
:12;
stop
@enduml
